SRC ?= csrc/bindings.cu
HEADERS := $(wildcard csrc/*.cuh)
NVCC ?= nvcc
ARCHS ?= SM100 SM103
# ARCH is kept as a convenient, backwards-compatible way to request one target.
ifneq ($(origin ARCH),undefined)
ARCHS := $(ARCH)
endif
PYTHON ?= python3
THUNDERKITTENS_ROOT ?= ./third_party/ThunderKittens
EXT_SUFFIX := $(shell $(PYTHON) -c "import sysconfig; print(sysconfig.get_config_var('EXT_SUFFIX'))")
OUT_SM100 ?= mok/_C_sm100$(EXT_SUFFIX)
OUT_SM103 ?= mok/_C_sm103$(EXT_SUFFIX)
NPROC_PER_NODE ?= 8

# Python/PyTorch binding
PYTHON_INCLUDES ?= $(shell $(PYTHON) -c "import sysconfig; print('-I', sysconfig.get_path('include'), sep='')")
PYTORCH_INCLUDES ?= $(shell $(PYTHON) -c "from torch.utils.cpp_extension import include_paths; print(' '.join(['-I' + p for p in include_paths()]))")
PYTORCH_LIBDIR ?= $(shell $(PYTHON) -c "from torch.utils.cpp_extension import library_paths; print(' '.join(['-L' + p for p in library_paths()]))")

# NVCC flags
NVCCFLAGS := -DNDEBUG -lineinfo
NVCCFLAGS += --expt-extended-lambda --expt-relaxed-constexpr
NVCCFLAGS += -Xcompiler=-Wno-psabi -Xcompiler=-fno-strict-aliasing
NVCCFLAGS += -forward-unknown-to-host-compiler -ftemplate-backtrace-limit=0
NVCCFLAGS += -std=c++20 -lrt -lpthread -ldl -lcuda -lcudadevrt -lcudart_static
NVCCFLAGS += -O3 --use_fast_math
NVCCFLAGS += -Xnvlink=--verbose -Xptxas=--verbose -Xptxas=--warn-on-spills
NVCCFLAGS += -I${THUNDERKITTENS_ROOT}/include
NVCCFLAGS += -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__
NVCCFLAGS += -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__
NVCCFLAGS += -DTORCH_API_INCLUDE_EXTENSION_H
NVCCFLAGS += $(PYTHON_INCLUDES) $(PYTORCH_INCLUDES) ${PYTORCH_LIBDIR}
NVCCFLAGS += -ltorch_python -ltorch_cuda -ltorch_cpu -ltorch -lc10_cuda -lc10
NVCCFLAGS += -shared -fPIC
NVCCFLAGS += -diag-suppress 3189 # for warnings generated by PyTorch C++ headers

SUPPORTED_ARCHS := SM100 SM103
INVALID_ARCHS := $(filter-out $(SUPPORTED_ARCHS),$(ARCHS))
ifneq ($(strip $(INVALID_ARCHS)),)
$(error Unsupported architecture(s) '$(INVALID_ARCHS)'; expected any of: $(SUPPORTED_ARCHS))
endif
ifeq ($(strip $(ARCHS)),)
$(error ARCHS must contain at least one of: $(SUPPORTED_ARCHS))
endif

OUTPUTS := $(foreach arch,$(ARCHS),$(OUT_$(arch)))

all: $(OUTPUTS)

test: $(OUTPUTS)
	$(PYTHON) -m torch.distributed.run --standalone --nproc-per-node=$(NPROC_PER_NODE) -m pytest -s tests/

$(OUT_SM100): $(SRC) $(HEADERS)
	$(NVCC) $(SRC) $(NVCCFLAGS) -DTORCH_EXTENSION_NAME=_C_sm100 -DKITTENS_SM100 -gencode arch=compute_100a,code=sm_100a -o $@

$(OUT_SM103): $(SRC) $(HEADERS)
	$(NVCC) $(SRC) $(NVCCFLAGS) -DTORCH_EXTENSION_NAME=_C_sm103 -DKITTENS_SM103 -gencode arch=compute_103a,code=sm_103a -o $@

clean:
	rm -f $(OUT_SM100) $(OUT_SM103)

.PHONY: all test clean
